version: "3.8"

services:
  backend:
    image: backend-image:latest
    container_name: backend
    ports:
      - "8888:8888"

  frontend:
    image: frontend-image:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
